### ISSUE TITLE
Encoder/Decoder

### ISSUE THREAD

**Issue by CMCDragonkai** [robtimus/php-multipart#1]
Is it possible to add decoding functionality. That is I'm going to receive `multipart/form-data` from a request and decode this data as well.

Python has something like this atm: https://github.com/requests/toolbelt/tree/master/requests_toolbelt/multipart

**Comment by robtimus** [comment]
At the moment this library is only for creating multipart requests. I do not have any plans to add any multipart parsing support any time soon.

After quick search on packagist I found https://packagist.org/packages/riverline/multipart-parser, maybe you can use this instead.
