### ISSUE TITLE
Add PHP 8.3 support

### ISSUE THREAD

**Issue by dkd-kaehm** [robtimus/php-multipart#2]
Please add PHP 8.3 support.

**Comment by robtimus** [comment]
I think that it should already work for PHP 8.3, it's just not tested. I will update the build action later today to include PHP 8.3. If any issues are found I will of course try to fix those, but I don't expect there will be any.

**Comment by robtimus** [comment]
The build action now also tests PHP 8.3. As expected the tests were successful without any changes.
